dubbo:
  application:
    name: user-service
  registry:
    protocol: zookeeper
    address: 192.168.19.129:2181
  protocol:
    port: 28812

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/v13?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: Bb55NP7afOPJgy+/fHTOd+rh7bCB+2LctpcTMWDWqtj66No9G+iL7Unn2+aCYPR6449xJtwmQ+EUVufBJHnb/w==
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filter:
        config:
          enabled: true
      connection-properties: config.decrypt=true;config.decrypt.key=${public-key}

  redis:
    host: 192.168.19.129
    port: 6379
    password: :java1902
    jedis:
      pool:
        max-active: 66




public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJZ0QFud4Be0cUPgeobW0sGrdActI422+4IwJTZiKzhomsK1G+3j0nxhq+S6+4DSfRmL2/CW3Jr7e2HSTAV/adMCAwEAAQ==
