dubbo:
  application:
    name: common-service
  registry:
    protocol: zookeeper
    address: 192.168.19.129:2181
  protocol:
    port: 28813

spring:
  mail:
    host: smtp.qq.com
    username: 3143720736@qq.com
    password: twkzoddnvqgiddcc
    default-encoding: UTF-8


  rabbitmq:
    host: 192.168.19.129
    port: 5672
    virtual-host: /java1902
    username: java1902
    password: 123

mail:
  fromAddr: 3143720736@qq.com
